/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DeviceId = string;
export type GenerationError = { 'ContentViolation' : null } |
  { 'QueueFull' : null } |
  { 'RateLimited' : null } |
  { 'ApiError' : string };
export type ImageId = string;
export interface ImageResult {
  'isCached' : boolean,
  'style' : string,
  'imageUrl' : string,
  'timestamp' : Timestamp,
  'prompt' : string,
  'imageId' : ImageId,
}
export interface RateLimitStatus {
  'remainingGenerations' : bigint,
  'dailyLimit' : bigint,
  'resetTimeNanos' : Timestamp,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface TrendingPrompt {
  'useCount' : bigint,
  'promptText' : string,
  'style' : string,
  'imageUrl' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'generateImage' : ActorMethod<
    [string, string, DeviceId],
    { 'ok' : ImageResult } |
      { 'err' : GenerationError }
  >,
  'getRateLimitStatus' : ActorMethod<[DeviceId], RateLimitStatus>,
  'getTrendingPrompts' : ActorMethod<[[] | [string]], Array<TrendingPrompt>>,
  'recordAdWatch' : ActorMethod<[DeviceId, string], boolean>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];