/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DeviceId = IDL.Text;
export const Timestamp = IDL.Int;
export const ImageId = IDL.Text;
export const ImageResult = IDL.Record({
  'isCached' : IDL.Bool,
  'style' : IDL.Text,
  'imageUrl' : IDL.Text,
  'timestamp' : Timestamp,
  'prompt' : IDL.Text,
  'imageId' : ImageId,
});
export const GenerationError = IDL.Variant({
  'ContentViolation' : IDL.Null,
  'QueueFull' : IDL.Null,
  'RateLimited' : IDL.Null,
  'ApiError' : IDL.Text,
});
export const RateLimitStatus = IDL.Record({
  'remainingGenerations' : IDL.Nat,
  'dailyLimit' : IDL.Nat,
  'resetTimeNanos' : Timestamp,
});
export const TrendingPrompt = IDL.Record({
  'useCount' : IDL.Nat,
  'promptText' : IDL.Text,
  'style' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'generateImage' : IDL.Func(
      [IDL.Text, IDL.Text, DeviceId],
      [IDL.Variant({ 'ok' : ImageResult, 'err' : GenerationError })],
      [],
    ),
  'getRateLimitStatus' : IDL.Func([DeviceId], [RateLimitStatus], ['query']),
  'getTrendingPrompts' : IDL.Func(
      [IDL.Opt(IDL.Text)],
      [IDL.Vec(TrendingPrompt)],
      ['query'],
    ),
  'recordAdWatch' : IDL.Func([DeviceId, IDL.Text], [IDL.Bool], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DeviceId = IDL.Text;
  const Timestamp = IDL.Int;
  const ImageId = IDL.Text;
  const ImageResult = IDL.Record({
    'isCached' : IDL.Bool,
    'style' : IDL.Text,
    'imageUrl' : IDL.Text,
    'timestamp' : Timestamp,
    'prompt' : IDL.Text,
    'imageId' : ImageId,
  });
  const GenerationError = IDL.Variant({
    'ContentViolation' : IDL.Null,
    'QueueFull' : IDL.Null,
    'RateLimited' : IDL.Null,
    'ApiError' : IDL.Text,
  });
  const RateLimitStatus = IDL.Record({
    'remainingGenerations' : IDL.Nat,
    'dailyLimit' : IDL.Nat,
    'resetTimeNanos' : Timestamp,
  });
  const TrendingPrompt = IDL.Record({
    'useCount' : IDL.Nat,
    'promptText' : IDL.Text,
    'style' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'generateImage' : IDL.Func(
        [IDL.Text, IDL.Text, DeviceId],
        [IDL.Variant({ 'ok' : ImageResult, 'err' : GenerationError })],
        [],
      ),
    'getRateLimitStatus' : IDL.Func([DeviceId], [RateLimitStatus], ['query']),
    'getTrendingPrompts' : IDL.Func(
        [IDL.Opt(IDL.Text)],
        [IDL.Vec(TrendingPrompt)],
        ['query'],
      ),
    'recordAdWatch' : IDL.Func([DeviceId, IDL.Text], [IDL.Bool], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };